"""OCR intake layer (demo-scope).

Reads SYNTHETIC scanned prior-authorization decision letters (generated in this
repo) and parses them into structured records. Everything here is demo-scope:
the letters are generated by ``generate_fixtures.py`` from templates in this
package, they contain only synthetic identifiers, and there is no PHI anywhere
in the pipeline. This layer is not RPA or an intake system operating against
real payer documents.
"""
